[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["SootyOwl <tyto@tyto.cc>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
Red-DiscordBot = "^3.4.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
